Changed helm repo URL to existing one.
helm/chartmuseum pull request #393
Opened 2020-11-24 19:00 UTC by karstengresch

old: https://kubernetes-charts.storage.googleapis.com
new: https://charts.helm.sh/stable

2020-11-24 19:00 UTC, thelinuxfoundation commented
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @karstengresch isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

2020-11-25 08:01 UTC, scbizu commented
Thanks you for the PR , please ensure to make the CLA happy .

2020-11-25 19:49 UTC, antoinedeschenes commented
The chart is now hosted there in fact: https://chartmuseum.github.io/charts

2020-11-30 14:48 UTC, jdolitsky requested changes
@antoinedeschenes

2020-11-30 14:48 UTC, jdolitsky commented on README.md
> +helm repo add stable https://charts.helm.sh/stable
@antoinedeschenes is correct. Can we switch this to
`helm repo add chartmuseum https://chartmuseum.github.io/charts` ?

2020-12-11 15:49 UTC, jdolitsky approved these changes

2020-12-11 15:49 UTC, merged