Fix duplicate versions for same chart
helm/chartmuseum pull request #492
Opened 2021-09-24 17:58 UTC by ninjadq

* The detailed issue is described in #450
* And there is a PR #454 fixed one scenario of this issue
* But there is another occasion in which users upload chart with prov
* in this PR is to handle this situation in a way similar to #454

Signed-off-by: DQ <dengq@vmware.com>

2021-09-25 10:51 UTC, scbizu commented
Hi @ninjadq , could you add some test cases for this PR ?

2021-09-25 15:03 UTC, ninjadq commented
hi @scbizu , added a case similar to chart only scenario

2021-09-25 18:32 UTC, scbizu requested changes

2021-09-25 18:33 UTC, scbizu commented
Added some review suggestions , thanks for your PR again

2021-09-26 03:39 UTC, ninjadq commented on pkg/chartmuseum/server/multitenant/handlers.go
> +		status, err := server.validateChartOrProv(repo, filename, force)
hi @scbizu,  The `server.validateChartOrProv` function not only check the existence of files but also check if their filename is improperly formatted. I just wonder if we can ignore this filename format check? If we can I will update this.

2021-09-28 10:18 UTC, scbizu commented on pkg/chartmuseum/server/multitenant/handlers.go
> +		status, err := server.validateChartOrProv(repo, filename, force)
Maybe we can move the filename validation out of `validateChartOrProv`  and put it to this loop  before `exist` checking? Like :

```Go

// check filename 

// existence checking
if exist { 
  cpFiles[filename] = &chartOrProvenanceFile{filename, content, ff.field} 
  continue 
}
// ... 

```

( BTW , the filename is constructed internally , I do not find any risks if we remove/ignore this validation)

2021-09-30 14:00 UTC, ninjadq commented on pkg/chartmuseum/server/multitenant/handlers.go
> +		status, err := server.validateChartOrProv(repo, filename, force)
hi @scbizu, thank you for your reply, I've updated the code and move the format check out of the `validateChartOrProv` func.

2021-09-30 16:15 UTC, scbizu commented on pkg/chartmuseum/server/multitenant/handlers.go
> +		status, err := server.validateChartOrProv(repo, filename, force)
Thank you XD

2021-09-30 16:16 UTC, scbizu approved these changes

2021-09-30 16:16 UTC, scbizu commented
LGTM 😎

2021-09-30 16:23 UTC, scbizu commented
Merging , the bad CI will be fixed in #482

2021-09-30 16:23 UTC, merged

2021-10-01 10:05 UTC, ninjadq commented
Thank you @scbizu, happy holidays

2021-10-01 10:09 UTC, scbizu commented
@ninjadq You too