feat: deprecate enforcesemver2 config option
helm/chartmuseum pull request #522
Opened 2022-01-22 20:55 UTC by cbuto

This is a follow up on #482 to fully "deprecate" the `--enforce-semver2` flag. It seems like some of the documentation work is capture in https://github.com/helm/chartmuseum/issues/485, which I can follow up on. 

Also, do we want a way to mark config options as deprecated and print warnings if they are set on startup?

2022-01-22 20:57 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/api.go
>  		return filename, &HTTPError{http.StatusInternalServerError, err.Error()}
While I get familiar with everything, should we return a `400` here and skip the call to `ChartVersionFromStorageObject` entirely?

2022-01-24 14:00 UTC, jdolitsky requested changes
> do we want a way to mark config options as deprecated and print warnings
yes, that would be great. Thanks @cbuto!

2022-01-24 14:25 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/api.go
>  		return filename, &HTTPError{http.StatusInternalServerError, err.Error()}
cool, fixed in 2f11e5029b735bc6a92a9fc566a732dfccfa9c01!

2022-01-24 14:25 UTC, cbuto commented on pkg/chartmuseum/server.go
> +		CacheInterval:  options.CacheInterval,
done in 2f11e5029b735bc6a92a9fc566a732dfccfa9c01 👍

2022-01-25 00:05 UTC, jdolitsky approved these changes
👍

2022-01-25 00:05 UTC, merged

2022-01-25 02:38 UTC, scbizu commented
Cool @cbuto , it really do me a fever 🥳

2022-01-25 02:40 UTC, scbizu commented
Cool @cbuto , it really do me a favor 🥳