refactor: use sync map instead for map string
helm/chartmuseum pull request #549
Opened 2022-02-09 15:31 UTC by nerdeveloper

Signed-off-by: nerdeveloper <odirionye@gmail.com>

2022-02-09 15:52 UTC, nerdeveloper commented
Yes

2022-02-09 17:26 UTC, cbuto commented on scripts/test.sh
> +    go test -race -v -covermode=atomic \
you'll need this set so the tests run!
```suggestion
    CGO_ENABLED=1 go test -race -v -covermode=atomic \
```

2022-02-10 03:11 UTC, scbizu commented
@nerdeveloper  And please fix your DCO verification ?

2022-02-10 03:12 UTC, scbizu requested changes

2022-02-10 03:12 UTC, scbizu commented on pkg/chartmuseum/server/multitenant/server.go
> +		InternalCacheStore     sync.Map
Can we wrap the `sync.Map` inside a specialized structure , for example `type memoryCacheStore struct { sync.Map }` maybe ,  and wrap the `Load` and `Store` func ?  Doing a type assertion every where  seems ugly though .

2022-02-17 11:42 UTC, cbuto commented
@nerdeveloper is there anything we can help with here?

2022-02-17 11:44 UTC, nerdeveloper commented
Yes, @cbuto, I tried to refactor to sync map, but the race condition still exists. i am having a hard time debugging this

2022-03-14 20:25 UTC, nerdeveloper commented
I am going to close this PR, as @cbuto has picked it and finished it

2022-03-14 20:25 UTC, closed without merging