feature add chart template and value api
helm/chartmuseum pull request #551
Opened 2022-02-11 13:18 UTC by zzhzero

2022-02-11 14:23 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/handlers.go
> +	filename := fmt.Sprintf("%s-%s.tgz", name, version)
there's an [existing function](https://github.com/helm/chartmuseum/blob/main/pkg/repo/chart.go#L45) for getting the chart filename that would be good to reuse here

2022-02-13 11:18 UTC, scbizu commented
The PR relates to #509 ?

2022-02-15 00:14 UTC, cbuto reviewed
few small nits around style

2022-02-15 00:14 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/server_test.go
> +	suite.Equal(404, res.Status(), fmt.Sprintf("200 GET %s/charts/mychart/0.1.1/templates", apiPrefix))
```suggestion
	suite.Equal(404, res.Status(), fmt.Sprintf("404 GET %s/charts/mychart/0.1.1/templates", apiPrefix))
```

2022-02-15 00:14 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/server_test.go
> +	suite.Equal(404, res.Status(), fmt.Sprintf("200 GET %s/charts/fakechart/0.1.0/templates", apiPrefix))
```suggestion
	suite.Equal(404, res.Status(), fmt.Sprintf("404 GET %s/charts/fakechart/0.1.0/templates", apiPrefix))
```

2022-02-15 00:14 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/server_test.go
> +	suite.Equal(404, res.Status(), fmt.Sprintf("200 GET %s/charts/mychart/0.1.1/values", apiPrefix))
```suggestion
	suite.Equal(404, res.Status(), fmt.Sprintf("404 GET %s/charts/mychart/0.1.1/values", apiPrefix))
```

2022-02-15 00:14 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/server_test.go
> +	suite.Equal(404, res.Status(), fmt.Sprintf("200 GET %s/charts/fakechart/0.1.0/values", apiPrefix))
```suggestion
	suite.Equal(404, res.Status(), fmt.Sprintf("404 GET %s/charts/fakechart/0.1.0/values", apiPrefix))
```

2022-02-15 00:14 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/api.go
> +func (server *MultiTenantServer) getChartFileName(log cm_logger.LoggingFn, repo string, name string, version string) (string, *HTTPError) {
small nit: whitespace around this function

2022-02-15 00:14 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/api.go
> +		return "", &HTTPError{http.StatusNotFound, "not found chart filename"}
```suggestion
		return "", &HTTPError{http.StatusNotFound, "chart filename not found"}
```

2022-02-15 00:14 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/api.go
> +		return "", &HTTPError{http.StatusNotFound, "not found chart filename"}
```suggestion
		return "", &HTTPError{http.StatusNotFound, "chart filename not found"}
```

2022-02-23 02:07 UTC, scbizu requested changes

2022-02-23 02:07 UTC, scbizu commented on pkg/chartmuseum/server/multitenant/handlers.go
> +	"helm.sh/helm/v3/pkg/chart/loader"
package imported here should be fmted .

2022-02-23 02:07 UTC, scbizu commented on pkg/chartmuseum/server/multitenant/handlers.go
> +			data = file.Data
Since we only need to seek the values , it seems that we can break here maybe ?

2022-02-23 02:09 UTC, scbizu commented
Another question , should this new handler be protected with the auth mechanism? 

/cc @cbuto

2022-03-04 17:00 UTC, cbuto commented
@scbizu we definitely need auth for these endpoints if they aren't already covered 👀

2022-03-06 17:20 UTC, cbuto approved these changes
lgtm after @scbizu's concerns are addressed! 🎉

2022-04-06 00:08 UTC, cbuto commented
want to give it another look @scbizu?

2022-04-07 03:26 UTC, scbizu approved these changes

2022-04-07 03:27 UTC, merged

2022-04-07 03:28 UTC, scbizu commented
LGTM  , let me do the re-format things , thank you @zzhzero 🎉