fix: Avoid data races for cacheEntries and index files
helm/chartmuseum pull request #556
Opened 2022-03-04 23:19 UTC by cbuto

Closes https://github.com/helm/chartmuseum/issues/546.

This should resolve the data races seen when running the test suite with the `-race` flag.

I took some of the work/feedback from https://github.com/helm/chartmuseum/pull/549 (thanks @nerdeveloper!) and added some additional changes to ensure we are locking when access the index file and cache entries.

---

I ran a few very small load tests locally.

1. Start chartmuseum locally
```
make build-mac && ./bin/darwin/amd64/chartmuseum --storage local --storage-local-rootdir /tmp
```

2. Run locust with 10 users/10 spawn rate

Here are the test run branches:

Test #8 = `main`
Test #9 = `fix/cache-race`
Test #10 = `main`
Test #11 = `fix/cache-race`

<img width="1667" alt="Screen Shot 2022-03-04 at 6 12 57 PM" src="https://user-images.githubusercontent.com/27781468/156854778-e3352b90-d06b-4250-9df2-94ab9c368cb0.png">

2022-03-07 03:00 UTC, scbizu commented
wow , looks good . 

I will spend some more time to read over this PR 👀   

However , it will conflict with #549 ?

2022-03-07 04:35 UTC, cbuto commented
> wow , looks good .
> 
> I will spend some more time to read over this PR 👀
> 
> However , it will conflict with #549 ?

Thanks! No rush at all. But yeah builds off of #549 and the initial work @nerdeveloper did.

2022-03-07 18:00 UTC, scbizu commented
I read some of this code , and have a question: what we do is actually make the rough-grain lock (RegenerationLock) to be the fine-grain lock (RepoLock &  IndexLock) ? But do we need to keep these rough-grain lock after we did this ?  

And I see the response time should be reduced literally , and this  optimization also related to the #396 .

2022-03-08 06:59 UTC, cbuto commented
> I read some of this code , and have a question: what we do is actually make the rough-grain lock (RegenerationLock) to be the fine-grain lock (RepoLock & IndexLock) ? But do we need to keep these rough-grain lock after we did this ?
> 
> And I see the response time should be reduced literally , and this optimization also related to the #396 .

good call! I think you are right, I removed the RegenerationLock in 48b75c77920e87d100eafa37d40f4bc049c1ee7d and it looks good. Some quick load test results showed no change but i don't think that lock was necessary anymore!

2022-03-08 16:35 UTC, scbizu commented
Looks much more comfortable now , I will review these all changes and make some tests on my mac this weekend .

2022-03-11 16:42 UTC, scbizu requested changes
The code here should be really careful for both writing and reviewing XD

2022-03-11 16:45 UTC, scbizu commented
@jdolitsky hihi , Could you also join the reviewing , I think it is an important fix or refactor PR .

2022-03-11 20:39 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/server_test.go
> +		e.RepoLock.Lock()
yep! missed that, changed it in 3619fdf7cf34529fafc8c59e227195c9c571b80b

2022-03-11 20:40 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/cache.go
> +func (m *memoryCacheStore) Load(key interface{}) (*cacheEntry, bool, error) {
yep definitely, its a bit weird returning an error. Fixed it in 3619fdf7cf34529fafc8c59e227195c9c571b80b

2022-03-11 20:41 UTC, cbuto commented on pkg/chartmuseum/server/multitenant/server_test.go
> +	return nil, nil
after fixing https://github.com/helm/chartmuseum/pull/556#discussion_r824878627, this return value will go away

2022-03-12 07:41 UTC, scbizu approved these changes
LGTM

2022-03-14 20:21 UTC, nerdeveloper approved these changes

2022-03-14 20:21 UTC, nerdeveloper commented
Awesome work there @cbuto

2022-04-07 04:08 UTC, cbuto commented
after rebasing with https://github.com/helm/chartmuseum/pull/551, some new data races showed up while running the tests (it seems to be flakey)

2022-04-08 17:51 UTC, jdolitsky approved these changes
fantastic. thanks for addressing this (apologies for delay in review!)

2022-04-08 19:16 UTC, cbuto commented
latest race fixed in 39464355182051cc2b5ebedd19bd46d5899dbfed, I ran the tests quite a few times just to be sure and it looks good!

2022-04-08 19:16 UTC, merged